(define (make-tree value left right) (list value left right))
(define (value tree) (car tree))
(define (left tree) (cadr tree))
(define (right tree) (caddr tree))
(define empty-tree? null?)

;problem 1

(define (make-clock hour minute)
  (let ((h hour)
        (min minute))
    (define (tick)
      (if (eq? min 59)
          (begin (set! min 0) (set! h (modulo (+ h 1) 24)))
          (set! min (+ 1 min)))
      (lambda (x)
        (if (eq? x 'time)
            time
            (if (eq? x 'military)
                military
                tick))))
    (define (time)
      (if (< h 12)
          (if (= h 0)
              (if (< min 10)
                  (string-append "12:0" (number->string min) " AM\n")
                  (string-append "12:" (number->string min) " AM\n"))
              (if (< min 10)
                  (string-append (number->string h) ":0" (number->string min) " AM\n")
                  (string-append (number->string h) ":" (number->string min) " AM\n")))
          (if (< min 10)
                  (string-append (number->string (- h 12)) ":0" (number->string min) " PM\n")
                  (string-append (number->string (- h 12)) ":" (number->string min) " PM\n"))))
    (define (military)
      (if (< h 10)
          (if (< min 10)
              (string-append "0" (number->string h) ":0" (number->string min) "\n")
              (string-append "0" (number->string h) ":" (number->string min) "\n"))
          (if (< min 10)
              (string-append (number->string h) ":0" (number->string min) "\n")
              (string-append (number->string h) ":" (number->string min) "\n"))))
    (define (dispatcher action)
      (cond ((eq? action 'tick) tick)
            ((eq? action 'time) time)
            ((eq? action 'military) military)))
    dispatcher)
)


;problem 2

(define (make-stack)
  (let ((lst '()))
    (define (empty?)
      (null? lst))
    (define (push x)
      (set! lst (cons x lst)) lst)
    (define (pop)
      (let ((element (car lst)))
        (begin (set! lst (cdr lst)) element)))
    (define (top)
      (car lst))
    (define (dispatcher action)
      (cond ((eq? action 'empty?) empty?)
            ((eq? action 'push) push)
            ((eq? action 'pop) pop)
            ((eq? action 'top) top)))
    dispatcher)
)


;problem 3

(define (eval-postfix p)
  (let ((postfix p)
        (ops (make-stack)))
    (define (process-operation op)
      (cond ((eq? op #\+)
             ((ops 'push) (+ ((ops 'pop)) ((ops 'pop)))))
            ((eq? op #\-)
             ((ops 'push)
              (let ((op2 ((ops 'pop)))
                    (op1 ((ops 'pop))))
                (- op1 op2))))
            ((eq? op #\*)
             ((ops 'push) (* ((ops 'pop)) ((ops 'pop)))))
            ((eq? op #\/)
             ((ops 'push)
              (let ((op2 ((ops 'pop)))
                    (op1 ((ops 'pop))))
                (/ op1 op2))))
            ((eq? op #\^)
             ((ops 'push)
              (let ((op2 ((ops 'pop)))
                    (op1 ((ops 'pop))))
                (expt op1 op2))))))
    (define (process-exp)
      (cond ((null? postfix)
             ((ops 'top)))
            ((number? (car postfix))
             (begin (( ops 'push) (car postfix))
                    (set! postfix (cdr postfix))
                    (process-exp)))
            (else
             (begin (process-operation (car postfix))
                    (set! postfix (cdr postfix))
                    (process-exp)))))
    (begin (process-exp) ((ops 'top))))
)


;problem 4

(define (dfs T)
  (let((s (make-stack)))
    (define (supplementary lst)
      (cond(((s 'empty?)) lst)
           (else (begin(let((T ((s 'pop))))
                         (if (not (null? (right T)))
                             ((s 'push) (right T)))
                         (if (not (null? (left T)))
                             ((s 'push) (left T)))
                         (supplementary (append lst (list (value T)))))))))
    (begin ((s 'push) T)
           (supplementary '())))
)


;problem 5

(define (make-queue)
  (let ((head '())
        (tail '()))
    (define (value n) (car n))
    (define (next n) (cdr n))
    (define (empty?) (null? head))
    (define (front) (value head))
    (define (enqueue x)
      (let ((new-node (cons x '())))
        (begin
          (if (empty?)
              (set! head new-node)
              (set-cdr! tail new-node))
          (set! tail new-node))))
    (define (dequeue)
      (let ((return (value head)))
        (if (eq? head tail)
            (begin (set! head '())
                   (set! tail '())
                   return)
            (begin (set! head (next head))
                   return))))
    (define (dispatcher method)
      (cond ((eq? method 'empty) empty?)
            ((eq? method 'enqueue) enqueue)
            ((eq? method 'dequeue) dequeue)
            ((eq? method 'front) front)))
    dispatcher)
)


(define (bfs T)
  (let ((Q (make-queue)))
    (define(supp k)
      (cond(((Q 'empty)) k)
           (else (begin (let ((T ((Q 'dequeue))))
                          (if (not (null? (left T)))
                              ((Q 'enqueue) (left T)))
                          (if (not (null? (right T)))
                              ((Q 'enqueue) (right T)))
                          (supp (append k (list (value T)))))))))
    (begin ((Q 'enqueue) T)
           (supp '())))
)